### ISSUE TITLE
Some common problems

### ISSUE THREAD

**Issue by adidasbrandon** [Dhruv-Techapps/auto-click#10]
Hello there are some common problems currently with the extension.

1: When you download the extension and try click it on the tab chrome bar it just doesn't take you anywhere you have to manually right click the extension and click 'options' for it to take you to the auto click page to type in your required site and xpath

2: When adding a new URL and Xpath if you add everything in and try to see if auto click is working it does not work the only way to get it to work is you have to manually hit 'enter' after typing in each field for example i type in google.com as the URL i must hit enter on that field for it to read it and so forth for each field xpath and interval and count.

If you could fix these issue's i'd greatly appreciate it thanks!

**Comment by Dhruv-Techapps** [comment]
Thank you for feed back. 
These are good suggestion, we will definitely add these features in further release

**Comment by heatjedi** [comment]
I've tried this still doesn't work.

**Comment by Dhruv-Techapps** [comment]
Hi,

We have developed above feature but still its under testing phase. and that's why this issue is still under open status.

We will soon finish testing and make it available for everyone.

**Comment by Dhruv-Techapps** [comment]
We have fixed and deployed. Please update your plugin
