### ISSUE TITLE
not clicking/ clicking only once

### ISSUE THREAD

**Issue by 21reyvillanueva** [Dhruv-Techapps/auto-click#11]
![capture](https://user-images.githubusercontent.com/33917279/33156674-f0409b66-d036-11e7-9d93-2dbfffa6f36e.PNG)

URL: https://youclick.alifelong.asia/site/click
//*[@id="clickbtn"]
0.005
99999999999999999999999999999999999

Windows 7
![system](https://user-images.githubusercontent.com/33917279/33156710-44e93e70-d037-11e7-92cc-3d9714e34ad7.PNG)

**Comment by Dhruv-Techapps** [comment]
Hi Friend,

We have added feature to do infinite click. You just need to enter -1 instead of positive no and it will do work for you.

Hope this works.
