### ISSUE TITLE
Select the option

### ISSUE THREAD

**Issue by 21ro** [Dhruv-Techapps/auto-click#14]
how to choose option 1 or others on black circle, and why be "undefined" on the other circle?
I have this kind of problem on another website, maybe someone can help me.
thank you..
![untitled](https://user-images.githubusercontent.com/34392855/33794987-291dd67c-dd09-11e7-9e1a-b5f928856aa2.png)

**Comment by Dhruv-Techapps** [comment]
Currently our Lite version works only for clicking element and not interact with Form fields like input, textarea, or dropdown. We are working on it to create PRO version of same which can do all short of stuff you want. So stay connected with us. We will publish PRO version soon in Jan 2018

**Comment by 21ro** [comment]
my problem about "undefined" already clear, great thanks to you. it's really helpful, and sure i'll stay connected..

**Comment by Dhruv-Techapps** [comment]
Thanks
