### ISSUE TITLE
I wish you make an autoclick extension like this in Mozilla too. 

### ISSUE THREAD

**Issue by BillyOnline** [Dhruv-Techapps/auto-click#15]
I got load of problems using chrome and I'm getting used to Mozilla. I wish you do made one for Mozilla users like us. By the way, awesome extension.

**Comment by Dhruv-Techapps** [comment]
First of all Thank you so much for showing interest in our extension. We will surely take this as positive and try to develop same for Mozilla 👍

**Comment by Dhruv-Techapps** [comment]
https://addons.mozilla.org/en-US/firefox/addon/auto-click-lite/
