### ISSUE TITLE
Won't click buttons like it used to

### ISSUE THREAD

**Issue by lazorbr** [Dhruv-Techapps/auto-click#18]
I use Auto Click Lite on a brazilian webpage and since Auto Click Lite last update it won't work on all buttons. Please help!

button 1 (works fine) xPath  **//*[@id="new-powerplay"]/div[3]/div[1]/div[2]/div[1]/a**
button 2 (no longer works) xPath **//*[@id="modal-music"]/div[2]/div/div[2]/div[1]/a[1]**

PS. buttons are behing a login/pass website

**Comment by Dhruv-Techapps** [comment]
Can you provide more information on same. As we are unable to figure out whats going wrong.

PS check out our new extension.
[Auto](https://chrome.google.com/webstore/detail/auto/iapifmceeokikomajpccajhjpacjmibe?hl=en)
