### ISSUE TITLE
Notifications

### ISSUE THREAD

**Issue by rayman89** [Dhruv-Techapps/auto-click#19]
Could you consider adding to the config page a way to toggle off the notifications for errors and the notifications when the clicks were done successfully? and maybe the ability to change how much time they are being shown? Thanks again.

**Comment by Dhruv-Techapps** [comment]
Notification feature is not liked by most of users and hence we have removed that. You can upgrade extension and it will be removed.

Do you need that feature back?

**Comment by rayman89** [comment]
Well I do not know all the error messages you could get but if there were some messages that would be useful for the user to be able to solve or realize what's the problem it might be useful otherwise is better without the notifications.

**Comment by Dhruv-Techapps** [comment]
Now you can turn on or off of notification based on your need. Check out our new extension with all new features.

[Auto](https://chrome.google.com/webstore/detail/auto/iapifmceeokikomajpccajhjpacjmibe?hl=en)
