### ISSUE TITLE
Check is not working

### ISSUE THREAD

**Issue by ghanta1996** [Dhruv-Techapps/auto-click#2]
Whenever I update URL. The check is not getting updated and I'm unable to use this extension

**Comment by corvette10077** [comment]
Hello,

I figured out that if you go to the main address bar at the top of Chrome, click on it,  and hit enter once you fill out the desired info below, it starts working.  Maybe just add this to your official instruction set.

Thanks,

- Dustin

**Comment by Dhruv-Techapps** [comment]
Yeah that's one of solution, But we have fixed it. Its available on chrome web-store please upgrade the same. Also this time we have checked with different xpath's as well you can find it in below link

[Auto Click](https://dhruv-techapps.github.io/auto-click/)
