### ISSUE TITLE
Cannot auto click when the webpage scroll more

### ISSUE THREAD

**Issue by quizasgg** [Dhruv-Techapps/auto-click#20]
Dear developer,

Sorry to bother you cause I cannot find your email (the link "inbox me" is 404). I'd like to use AutoClick to click the "more" in Quora. But when the webpage scroll down, the new answer cannot be clicked by AutoClick.
Please see the attachments for more details, Thank you.

BR.
  
![1](https://user-images.githubusercontent.com/35323931/34810641-a02cd46a-f6d7-11e7-97ce-11d79c55ecb4.png)
![2](https://user-images.githubusercontent.com/35323931/34810642-a0656ba4-f6d7-11e7-8c65-607a87e95df7.png)
![3](https://user-images.githubusercontent.com/35323931/34810643-a0a0eb52-f6d7-11e7-8d6d-7318df568281.png)

**Comment by Dhruv-Techapps** [comment]
Try this
xPath: //span[contains(text(),'(more)')]
RepeatInterval :- 1 sec

Email: Dhruv.techapps@gmail.com

**Comment by quizasgg** [comment]
Hi Dhruv, sorry to bother you, but this issue still exist.
You can see from the screenshoot. It happend when the webpage scroll down, the new information will be load.
Thank you in advance.
![1](https://user-images.githubusercontent.com/35323931/35311133-e45eaca4-00ef-11e8-9ccc-0bb1f94a39c2.png)

**Comment by Dhruv-Techapps** [comment]
Extension retry for 5 times and stops. 
Now you can control the retry count for extension from settings menu.

[Auto](https://chrome.google.com/webstore/detail/auto/iapifmceeokikomajpccajhjpacjmibe?hl=en)
