### ISSUE TITLE
Don't work for a button.

### ISSUE THREAD

**Issue by jcorona-gh** [Dhruv-Techapps/auto-click#24]
Hello,

Thanks for your time on the extension.

Having issues getting it to work onto a refresh button inside some divisions, here's a copy of the code trying to shed some light:

<div class="pks-tbitemR">
                            <button id="viewCartButton" pks-ctrl-type="kendoButton" data-role="button" class="k-button" role="button" aria-disabled="false" tabindex="0" style="visibility: visible;">View Cart (0)</button>
                            <button id="submitRequestsButton" pks-ctrl-type="kendoButton" data-role="button" class="k-button" role="button" aria-disabled="false" tabindex="0"><span class="k-icon k-i-tick" style="padding-right: 4px"></span>Submit</button>
                            <button id="luckyRequestsButton" pks-ctrl-type="kendoButton" style="display: none;" data-role="button" class="k-button" role="button" aria-disabled="false" tabindex="0"><span class="k-icon k-i-ungroup"></span>Lucky</button>
                            <button id="refreshButton" pks-ctrl-type="kendoButton" title="Refresh Schedule" data-role="button" class="k-button" role="button" aria-disabled="false" tabindex="0"><img src="Images/vac_part_refresh.gif" alt="Refresh"></button>
                        </div>

It is the inner div, as it has 4 levels, suspecting this is the problem for the syntax. Copied xpath as explained in tutorial, for: //*[@id="refreshButton"] ; but getting element not found error always. Tried many different "logical" ways without success.

Would appreciate the help. Thanks in advance.

JC

**Comment by jcorona-gh** [comment]
Oops, html spoiled prev comment, sorry, just replaced < for &lt. Here goes:

Hello,

Thanks for your time on the extension.

Having issues getting it to work onto a refresh button inside some divisions, here's a copy of the code trying to shed some light:

<pre>
&ltdiv class="pks-tbitemR">
                            &ltbutton id="viewCartButton" pks-ctrl-type="kendoButton" data-role="button" class="k-button" role="button" aria-disabled="false" tabindex="0" style="visibility: visible;">View Cart (0)&lt/button>
                            &ltbutton id="submitRequestsButton" pks-ctrl-type="kendoButton" data-role="button" class="k-button" role="button" aria-disabled="false" tabindex="0"><span class="k-icon k-i-tick" style="padding-right: 4px">&lt/span>Submit&lt/button>
                            &ltbutton id="luckyRequestsButton" pks-ctrl-type="kendoButton" style="display: none;" data-role="button" class="k-button" role="button" aria-disabled="false" tabindex="0">&ltspan class="k-icon k-i-ungroup">&lt/span>Lucky&lt/button>
                            &ltbutton id="refreshButton" pks-ctrl-type="kendoButton" title="Refresh Schedule" data-role="button" class="k-button" role="button" aria-disabled="false" tabindex="0">&ltimg src="Images/vac_part_refresh.gif" alt="Refresh">&lt/button>
                        &lt/div>
</pre>
It is the inner div, as it has 4 levels, suspecting this is the problem for the syntax. Copied xpath as explained in tutorial, for: //*[@id="refreshButton"] ; but getting element not found error always. Tried many different "logical" ways without success.

Would appreciate the help. Thanks in advance.

JC

**Comment by Dhruv-Techapps** [comment]
Hi jcorona,

I see no issue in your xpath but not sure why its not able to find the element. Can you try other way.

* open developer console using F12
* open Element Tab
* right click button and select inspect.
* right click element focused on developer console and select copy xpath.

Check below video for more details
https://www.youtube.com/edit?o=U&video_id=jN3-SyWWPzs
