### ISSUE TITLE
Provide Source Code for the auto-click Extension

### ISSUE THREAD

**Issue by pierow2k** [Dhruv-Techapps/auto-click#27]
While the repository has a code of conduct, a license, a wiki, a privacy policy and other items typically found in an open source repository on GitHub, this repository seems to be lacking any source code for the actual auto-click plugin itself.

**Comment by gingerbeardman** [comment]
+1

**Comment by Dhruv-Techapps** [comment]
Sorry Sir. Our extension is freeware only and we are here to help you any addon feature you require. You don't have to really work on it.

**Comment by gingerbeardman** [comment]
No problem. I extracted the source code from the extension.

**Comment by Iey4iej3** [comment]
Dear developers,

Could you please clarify the license of your extension? There is an Apache license here and on your website, it is said that

> Designed and built with all the love in the world by the Dhruv Techapps Team.
> Currently v3.2.0. Code licensed Apache 2.0, docs CC BY 3.0.

What code is licensed Apache 2.0 and what code is proprietary? And @gingerbeardman the extracted code is minified anyway.
