### ISSUE TITLE
it doesn't work

### ISSUE THREAD

**Issue by teajoe** [Dhruv-Techapps/auto-click#28]
![untitled](https://user-images.githubusercontent.com/36964341/36856720-47ea3b2c-1d3c-11e8-941d-c6274ad623b9.png)

when I follow instruction of auto click, it doesn't work on this website, please help, thanks

**Comment by teajoe** [comment]
here is another pic, the circled one is assign above forum for autoclick, but it didn't work
![untitled](https://user-images.githubusercontent.com/36964341/36857152-6b84bc1e-1d3d-11e8-9dad-e483c3c93900.png)

**Comment by Dhruv-Techapps** [comment]
We will look into it.

**Comment by Dhruv-Techapps** [comment]
Can you please provide values you used. We are not able to see value correctly in screen shot
