### ISSUE TITLE
xPath example

### ISSUE THREAD

**Issue by Riztard** [Dhruv-Techapps/auto-click#31]
please add more example like these, i need to figure it out by myself to combine it

html/body/div[8]/center[1]/div[1]/div[1]/a[1]/input[@value='Baca Mode Full Page']

**Comment by mtbduri** [comment]
yes please.  I am a novice but would like examples of xPath for Start Time, STOP xPath, STOP Value

**Comment by Dhruv-Techapps** [comment]
Please refer [xPath](https://github.com/Dhruv-Techapps/auto-click/wiki/xPath)
