### ISSUE TITLE
Click inside iframe

### ISSUE THREAD

**Issue by doodyr** [Dhruv-Techapps/auto-click#33]
I'm trying to click inside an iframe, but I don't know if I doing wrong or if this is an issue.

Could you help me?

![image](https://user-images.githubusercontent.com/36056453/37253435-7cab1f76-2510-11e8-88f9-cb309648a283.png)

**Comment by Dhruv-Techapps** [comment]
You need to enable iframe check from settings screen. Also if the Iframe have different URL . You need to configure with that URL
