### ISSUE TITLE
It loads the URL of Page so does not work with Responsive Modal window. Please do something for it.

### ISSUE THREAD

**Issue by Tanush7** [Dhruv-Techapps/auto-click#39]
I am trying to use this in my google sheets to save all my emails in google drive so there is an addon in google sheets which save emails automatically but I have to click on the run button manually to save 20 emails in every one minute. So I tried to use this Auto click, it has everything I want time interval and where to click but the problem is it reloads the page whenever it has to start so that addon modal disappears everytime the page reloads. So what i need is basically i will open the google sheet and that addon in the same window and fill in the auto click detail about which button has to be clicked for a specific period of time and time interval. And without reloading the page it will start doing the process. So if that is possible then please do it. My heart appreciation for you.

**Comment by Dhruv-Techapps** [comment]
You can keep the repeat interval little longer so extension will retry after that much specific interval of time. Also you can email us your scenario so we can figure out how we can help you.
