### ISSUE TITLE
If/Then

### ISSUE THREAD

**Issue by AB299** [Dhruv-Techapps/auto-click#42]
If there anywhere to add an if/then for written text below the button. So for example if there's a red button that says "click here" below, but the text is not apart of the button and a green button that says "don't click here" below but not apart of the button the system could tell which one to click. Especially if they moved around the page.

**Comment by Dhruv-Techapps** [comment]
Sorry we didnt got your issue. Can you please send in detail on dhruv.techapps@gmail.com. We will surely help you with your issue
