### ISSUE TITLE
Condition not working for me

### ISSUE THREAD

**Issue by jmatillano** [Dhruv-Techapps/auto-click#44]
i use auto click in this pay to click site and i successfully able to use auto clicker to click the ad link but the site has a timer before you are suppose to click again the ad link. After the timer finishes the countdown, it display "You can click now." i added this to the condition of my auto click entry but its not working.

**Comment by Dhruv-Techapps** [comment]
Try to add repeat interval to match the timer. Auto click don't run always in background. Once it has completed it job it goes off.

**Comment by jmatillano** [comment]
ok thanks
