### ISSUE TITLE
The first page goes, but the next page doesn't work....... help me﻿

### ISSUE THREAD

**Issue by CHEERLESS777** [Dhruv-Techapps/auto-click#46]
The first page goes, but the next page doesn't work....... help me﻿

ex) URL : https://dhruv-techapps.github.io/auto-click/
      Xpath : /html/body/section[2]/ul[2]/li[3]/a                 (text site)
             -> going
     but, 
     next URL : https://dhruv-techapps.github.io/auto-click/test/index.html          (text site)
      Xpath : //*[@id="button"]                                                                       (I'M BUTTON WITH ID)
       This page doesn't work................... not count (I'M BUTTON WITH ID) !!

**Comment by Dhruv-Techapps** [comment]
Please use latest extension https://chrome.google.com/webstore/detail/auto-click-auto-fill/iapifmceeokikomajpccajhjpacjmibe
