### ISSUE TITLE
Not working in Firefox

### ISSUE THREAD

**Issue by jpinnix** [Dhruv-Techapps/auto-click#47]
Firefox 62 for Mac

It adds the button to the toolbar, and when I go to Preferences, I can't add anything. This is all I see:
<img width="580" alt="auto click 2018-06-06 16-02-56" src="https://user-images.githubusercontent.com/4436/41065128-3f191b68-69a3-11e8-9e45-e43f59389f05.png">

It appears that the body of the table is empty:
<img width="298" alt="auto click 2018-06-06 16-06-14" src="https://user-images.githubusercontent.com/4436/41065231-934ccda6-69a3-11e8-9cfe-2daa2aa9c094.png">

**Comment by Dhruv-Techapps** [comment]
Hi ,

we are not supporting firefox for now
