### ISSUE TITLE
not work in firefox 32 bit system

### ISSUE THREAD

**Issue by Zshan21** [Dhruv-Techapps/auto-click#48]
Auto click not work for me since last night.There is no option for adding a link.
Please give me solution
![capture 444](https://user-images.githubusercontent.com/40045233/41138684-926e3998-6b00-11e8-86a9-5c3e419911d4.PNG)

**Comment by Dhruv-Techapps** [comment]
We are no longer supporting firefox for now.

**Comment by abunasser2** [comment]
why i need firefox
