### ISSUE TITLE
I can't download extension on chrome store

### ISSUE THREAD

**Issue by linhndd** [Dhruv-Techapps/auto-click#49]
Hi,

Thanks for share great tool. But I cant download extension with link in about page ? How to build it to extension for chrome ? I only found Auto fill from Chrome store.

Please update link chrome store or share extension build file.

Thanks for advance

**Comment by Dhruv-Techapps** [comment]
Please try this link.

https://chrome.google.com/webstore/detail/auto/iapifmceeokikomajpccajhjpacjmibe

**Comment by alexandrecazaurang** [comment]
Hi,
The app no longer seem to be available on the chrome web store, could you please reupload it?
Thanks a lot,

**Comment by alexandrecazaurang** [comment]
Hi seems to be back ! thanks

**Comment by Dhruv-Techapps** [comment]
Yes I just mailed Google regarding same and they brought back. Thanks to
everyone who was supporting me.
