### ISSUE TITLE
Auto Click options page not working

### ISSUE THREAD

**Issue by syedsalmanhafiz** [Dhruv-Techapps/auto-click#52]
![image](https://user-images.githubusercontent.com/41298526/42765909-b609b5fe-8936-11e8-8db0-5b8fdb7f9cb1.png)

**Comment by Dhruv-Techapps** [comment]
Please use latest auto click extension https://chrome.google.com/webstore/detail/auto-click-auto-fill/iapifmceeokikomajpccajhjpacjmibe
