### ISSUE TITLE
jetleech.net problem

### ISSUE THREAD

**Issue by oleedd** [Dhruv-Techapps/auto-click#55]
It doesn't work for this button.
![screenshot](https://user-images.githubusercontent.com/36125949/45264799-f5d8b600-b44a-11e8-9b89-f04f818626d2.png)
To reproduce just paste http://uploaded.net/file/0fpyh5c5 into generation area and press "Download" button.
Please fix this.

**Comment by oleedd** [comment]
Very nice extension. The problem is solved.
It automatically chooses //*[@id="link0"]/b[1]/a[1]/font[1]
But if remove font[1] => with //*[@id="link0"]/b[1]/a[1]/ it works.

If after pressing a button the download windows appears. Possible to autoclose that tab after confirming or canceling a download?

**Comment by Dhruv-Techapps** [comment]
no Its not possible to control new tab from existing tab
