### ISSUE TITLE
not working in Chrome Version 70.0.3538.77 (Official Build) (64-bit)

### ISSUE THREAD

**Issue by 016** [Dhruv-Techapps/auto-click#57]
see some js error in inspect, can u plz fix it?

many thx.

<img width="1251" alt="screen shot 2018-11-08 at 9 52 11 pm" src="https://user-images.githubusercontent.com/7589575/48202726-a5c19580-e3a0-11e8-8d57-ba960256878b.png">

**Comment by dharmesh-hemaram** [comment]
We have fixed this issue can you please reinstall the latest version and check again.
