### ISSUE TITLE
open new page

### ISSUE THREAD

**Issue by kuntalrambabu** [Dhruv-Techapps/auto-click#59]

**Comment by kuntalrambabu** [comment]
if i have some href link that can be 100 and i want  to open in a new page every link how i open

**Comment by dharmesh-hemaram** [comment]
You can run this scripts in developer console to set the link to open in new tab
document.querySelectorAll("a").forEach(function(a){
if(a.getAttribute("target") !== "_blank"){
	a.setAttribute("target","_blank");
}
});
