### ISSUE TITLE
How to upload file?

### ISSUE THREAD

**Issue by trungpc** [Dhruv-Techapps/auto-click#60]
Hi,

I try my best so I couldn't get upload file.

Anyone show me how to get it?

Thank!

**Comment by dharmesh-hemaram** [comment]
Upload file feature is not available in the current version.

**Comment by Iey4iej3** [comment]
Is it possible to autoclick the file chooser? This seems plausible, in view of [this SO answer](https://stackoverflow.com/a/16215950).

**Comment by Iey4iej3** [comment]
OK, it could be triggered by `MouseEvents::click`.
