### ISSUE TITLE
weird xpath and wont autoclick.

### ISSUE THREAD

**Issue by asianhero117** [Dhruv-Techapps/auto-click#72]
Hi I just subscribe this extension and everything works fine. I just sometimes got xpath like this /html/body/main/div/div/button and it wont autoclick. But if I get soemthing like this //*[@id="activateLicenseButton"] it works perfectly. Any thoughts on /html/body/main/div/div/button ?

**Comment by dharmesh-hemaram** [comment]
Yes. You can use //*[@id="activateLicenseButton"]

Please refer Wiki page for different [Xpath](https://github.com/Dhruv-Techapps/auto-click/wiki/xPath))
