### ISSUE TITLE
Delay before clicking

### ISSUE THREAD

**Issue by alexgonca** [Dhruv-Techapps/auto-click#8]
Hi Dharmesh,

First, thank you so much for this extension!
I have a suggestion.
It would be very useful if we could specify a time delay before the extension clicks an object.
Some pages need some time to load dynamic content.
It would be great if we could specify a delay of 5 seconds, for instance, before any button or link is clicked by the extension.
What do you think?

Thank you so much again!
Alex.

**Comment by dharmesh-hemaram** [comment]
Hi Alex,

Thanks for checking out AutoClick Extension. We have already created milestone for same and it will be available soon. :)

**Comment by Dhruv-Techapps** [comment]
This feature is published please update
