### ISSUE TITLE
wont click the button

### ISSUE THREAD

**Issue by rendon23** [Dhruv-Techapps/auto-click#9]
Ive done litterally everything right from youtube videos help?

**Comment by dharmesh-hemaram** [comment]
Can you please provide us four param's
URL:
xPath:
Interval:
Time:

**Comment by rendon23** [comment]
URL: https://yeezysupply.com/
Xpath: //*[@id="js-main"]/div/form/div/div[3]/input[2]
interval: 1
time: 1

**Comment by Dhruv-Techapps** [comment]
xPath given is wrong. It dont match any element on page. Can you please provide information on which button you tried to use our extension

**Comment by ilmb56** [comment]
isn't working button isn't being clicked.

**Comment by rendon23** [comment]
Am i copying the wrong thing?

**Comment by ilmb56** [comment]
i don't know what the issue is

**Comment by Dhruv-Techapps** [comment]
Yes there are no `form` in  `js-main` tag.
